apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kustomize-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for Kustomize-based applications
  sourceRepos:
    - https://github.com/arramandhanu/argocd-lab.git
  destinations:
    - namespace: nginx-kustomize-*
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true
