apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ app-name }}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/arramandhanu/argocd-lab.git
    targetRevision: main
    path: {{ app-path }}
    helm:
      valueFiles:
        - chart-values/dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ app-name }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

