apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: repos
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-username/argocd-lab.git
    targetRevision: main
    path: repos
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

