{{- if .Values.pdb.enabled }}
{{- $pdbName := include "nginx.fullname" . }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $pdbName }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
spec:
  {{- if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- else }}
  minAvailable: {{ .Values.pdb.minAvailable | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nginx.selectorLabels" . | nindent 6 }}
{{- end }}
