apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-kustomize-prod
  namespace: argocd
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: kustomize-prod
    environment: prod
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/arramandhanu/argocd-lab.git
    targetRevision: main
    path: kustomize/nginx/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-kustomize-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
